microservices:
  maps: http://localhost:9191
  pricing: http://pricing-service

server:
  port: 8080

spring:
  application:
    name: vehicles-api

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    service-url:
      default-zone: http://localhost:8761/eureka/