server:
  port: 8082

spring:
  application:
    name: dog-service
  datasource:
    url: jdbc:h2:mem:prices
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    service-url:
      default-zone: http://localhost:8761/eureka/