server:
  port: 9191

spring:
  application:
    name: boogle-maps

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    service-url:
      default-zone: http://localhost:8761/eureka/
